#ifndef PINCONFIG
#define PINCONFIG

#include <Arduino.h>

#define PIN_MOTOR_FWD1 GPIO_NUM_33
#define PIN_MOTOR_REV1 GPIO_NUM_32
#define PIN_MOTOR_FWD3 GPIO_NUM_13
#define PIN_MOTOR_REV3 GPIO_NUM_27
#define PIN_MOTOR_FWD2 GPIO_NUM_26
#define PIN_MOTOR_REV2 GPIO_NUM_25

#define CHANNEL_MOTOR_FWD1 0
#define CHANNEL_MOTOR_REV1 1
#define CHANNEL_MOTOR_FWD2 2
#define CHANNEL_MOTOR_REV2 3
#define CHANNEL_MOTOR_FWD3 4
#define CHANNEL_MOTOR_REV3 5


#endif